export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const REMOVE_TRANSACTIONS = 'REMOVE_TRANSACTIONS';
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const REMOVE_ACCOUNTS = "REMOVE_ACCOUNTS";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";